### ISSUE TITLE
张量尺寸错误 RuntimeError: output with shape [1, 128, 128] doesn't match the broadcast shape [3, 128, 128]

### ISSUE THREAD

**Issue by luizz8416** [bytedance/DWSF#1]
完整的报错信息
Train Epoch: 0 [0/394]  D_loss: 1.4287535548210144 = DisF:0.9066857099533081 + DisT:0.5220678448677063
        En_De_loss: 0.6271777153015137 = Gen:0.5223720073699951 + En:1.126967191696167=MSE-0.49768513441085815+MSSIM-125.85639953613281, De:0.4012618660926819
Traceback (most recent call last):
  File "train_ed.py", line 90, in <module>
    for batch_idx, batch_data in enumerate(train_loader):
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\pyqt\DWSF-main\utils\dataset.py", line 29, in __getitem__
    image = self.tranform(image)
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torchvision\transforms\transforms.py", line 270, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torchvision\transforms\functional.py", line 360, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "E:\anaconda3\envs\DWSF\lib\site-packages\torchvision\transforms\functional_tensor.py", line 940, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 128, 128] doesn't match the broadcast shape [3, 128, 128]

**Comment by SodalimeZero** [comment]
I also encountered this problem at runtime. I think it was caused by the fact that the paper was using a color image dataset. I used the following to fix it:
delete the black and white images in the dataset because they have a channel count of 1.

**Comment by luizz8416** [comment]
> I also encountered this problem at runtime. I think it was caused by the fact that the paper was using a color image dataset. I used the following to fix it: delete the black and white images in the dataset because they have a channel count of 1.
谢谢你，我之后再训练分割模型的时候发现耗时非常久（大概4-5天），请问你完成分割模型的训练了吗？

**Comment by SodalimeZero** [comment]
没有。。我看论文用的A100显卡，我实验室只有两张3090，还要大家一起用

**Comment by SodalimeZero** [comment]
其实我认为作者可以公开一下训练好的模型hhh

**Comment by Map1e0823** [comment]
至少给个差不多的预训练嘛2333

**Comment by Ontheroad123** [comment]
> I also encountered this problem at runtime. I think it was caused by the fact that the paper was using a color image dataset. I used the following to fix it: delete the black and white images in the dataset because they have a channel count of 1.
dataset.py中将图像读取设置为RGB
image = Image.open(self.filepath+'/'+self.filelist[item]).convert('RGB')

**Comment by Jraytheon01** [comment]
> > I also encountered this problem at runtime. I think it was caused by the fact that the paper was using a color image dataset. I used the following to fix it: delete the black and white images in the dataset because they have a channel count of 1.
> > 谢谢你，我之后再训练分割模型的时候发现耗时非常久（大概4-5天），请问你完成分割模型的训练了吗？

请问你之后完成训练了吗

**Comment by Ontheroad123** [comment]
> > > I also encountered this problem at runtime. I think it was caused by the fact that the paper was using a color image dataset. I used the following to fix it: delete the black and white images in the dataset because they have a channel count of 1.
> > > 谢谢你，我之后再训练分割模型的时候发现耗时非常久（大概4-5天），请问你完成分割模型的训练了吗？
> 
> 请问你之后完成训练了吗

我只是训练了一个demo只有1000张，和你的情况不一样
